.\"
.\" Copyright (C) 2002-2003 by Lucent Technologies
.\"
.TH INDEX UNITY "" "UNITY User's Manual"
.nf
.in 0
                    - menu   access to UNITY commands.  .... umenu
    attribute in one or/ -   alter the value of an ........................ alter
 do elementary statistical   analysis on numeric/ - .................... stat
       - print description   and/or data for a UNITY/ ............ display,dis
   Intro to UNITY commands   application programs.  .................... Intro
  UNITY tables.  - compute   arithmetic expressions on ........ compute
 sort table on a specified   attribute.  - ........................................................ asort
  - produce an index on an   attribute for a UNITY/ .................... index
   - alter the value of an   attribute in one or more/ ........ alter
attribute values for given   attribute.  - join/split ............ merge,unmerge
  attribute.  - join/split   attribute values for given .... merge,unmerge
  - find set difference of   attributes on two UNITY/ ............ setdiff
       analysis on numeric   attributes.  /statistical ........ stat
       - check UNITY table   attributes.  ............................................................ ucheck
   - erase UNITY table and   auxiliary files.  ........................................ erase-table,et
- join two existing tables   based on regular/ ........................................ regjoin
                 table.  -   change format of a UNITY ............ format,uformat
            attributes.  -   check UNITY table ........................................ ucheck
   - introduction to UNITY   commands and application/ ........ Intro
 print man pages for UNITY   commands.  - ............................................................ uman
    - menu access to UNITY   commands.  .................................................................... umenu
                 table.  -   compile a validation ............................ valcmp
   expressions on UNITY/ -   compute arithmetic .................................... compute
         packet format.  -   convert records to stream ........ packet
       to tuple format.  -   converts data from packet ........ tuple
- print description and/or   data for a UNITY table.  ............ display,dis
       format.  - converts   data from packet to tuple ........ tuple
table name,attributes, and   data types.  -  define .................... table
   name,attributes, and/ -   define table ............................................................ table
-  interactive UNITY table   definition.  ............................................................ maketable
    from a UNITY table.  -   delete one or more records .... delete,udelete
    stored under/ - make a   delta to a UNITY table .................... udelta
   a UNITY table.  - print   description and/or data for  display,dis
     two UNITY/ - find set   difference of attributes on  setdiff
       - single and double   distributions on a UNITY/ ........ dist,ddist
       UNITY/ - single and   double distributions on a ........ dist,ddist
                 table.  -   edit records in a UNITY ................ uedit
 analysis on numeric/ - do   elementary statistical .................... stat
                 table.  -   enter records into a UNITY .... uenter
                         -   erase UNITY index files.  ........ erase-index,ei
       auxiliary files.  -   erase UNITY table and ........................ erase-table,et
       regular/ - join two   existing tables based on ............ regjoin
           - outerjoin two   existing UNITY tables.  ................ outerjoin
                - join two   existing UNITY tables.  ................ ujoin,join
      - compute arithmetic   expressions on UNITY/ ........................ compute
   tables based on regular   expressions.  /two existing  regjoin
 load records between UNIX   file and a UNITY table.  ............ load
  a UNITY table and a UNIX   file.  /records between ................ unload
       - erase UNITY index   files.  ................................................................................ erase-index,ei
 UNITY table and auxiliary   files.  - erase ................................................ erase-table,et
attributes on two UNITY/ -   find set difference of .................... setdiff
                  - change   format of a UNITY table.  ........ format,uformat
  records to stream packet   format.  - convert .................................... packet
 data from packet to tuple   format.  - converts ................................ tuple
 UNITY table  - vertically   formatted presentation of a  catalog
           UNITY table.  -   formatted presentation of a  uprint,print
     UNITY table - numeric   formatted print on a ......................... nprintf
              - High Level   Function Interface.  ............................ Uinthl
          UNITY record.  -   function to validate a .................... val
      attribute values for   given attribute.  ........................................ merge,unmerge
             Interface.  -   High Level Function ................................ Uinthl
             - erase UNITY   index files.  ........................................................ erase-index,ei
       UNITY/ - produce an   index on an attribute for a  index
           UNITY table.  -   insert new records into a ........ insert
            definition.  -   interactive UNITY table ................ maketable
     - High Level Function   Interface.  ................................................................ Uinthl
               - Low Level   Interface.  ................................................................ Uintll
           commands and/ -   introduction to UNITY ........................ Intro
       based on regular/ -   join two existing tables ............ regjoin
                tables.  -   join two existing UNITY ................ ujoin,join
   for given attribute.  -   join/split attribute values  merge,unmerge
                    - High   Level Function Interface.  .... Uinthl
                     - Low   Level Interface.  ........................................ Uintll
       file and a UNITY/ -   load records between a UNIX  load
                         -   Low Level Interface.  ........................ Uintll
              commands.  -   menu access to UNITY ............................ umenu
   types.  -  define table   name,attributes, and data ........ table
   statistical analysis on   numeric attributes.  ............................ stat
          UNITY tables.  -   outerjoin two existing .................... outerjoin
 convert records to stream   packet format.  - ........................................ packet
      - converts data from   packet to tuple format.  ............ tuple
               - print man   pages for UNITY commands.  .... uman
    - vertically formatted   presentation of a UNITY/ ............ catalog
       table.  - formatted   presentation of a UNITY ................ uprint,print
    data for a UNITY table   print description and/or ............ display,dis
              commands.  -   print man pages for UNITY ........ uman
       - numeric-formatted   print on UNITY tables.  ................ nprintf
          - user-formatted   print on UNITY tables.  ................ uprintf
-attribute for UNITY table   produce an index on an .................... index
  commands and application   programs.  /to UNITY ............................ Intro
        - do selection and   projection on a UNITY/ .................... uselect,select
       to validate a UNITY   record.  - function ................................ val
                         -   record validator.  .................................... validate
an attribute in one or more   records.  /the value of ................ alter
table and a UNIX/ - unload   records between a UNITY ................ unload
       and a UNITY/ - load   records between a UNIX file  load
      - delete one or more   records from a UNITY/ ........................ delete,udelete
                    - edit   records in a UNITY table.  .... uedit
      table.  - insert new   records into a UNITY ............................ insert
           table.  - enter   records into a UNITY ............................ uenter
        format.  - convert   records to stream packet ............ packet
  existing tables based on   regular expressions.  /two .... regjoin
 store a UNITY table under   SCCS.  - ............................................................................ uadmin
a UNITY table stored under   SCCS.  - make a delta to ............ udelta
a UNITY table stored under   SCCS.  - get a version of ........ uget
      a UNITY table.  - do   selection and projection on  uselect,select
 attributes on two/ - find   set difference of ........................................ setdiff
     distributions on a/ -   single and double ........................................ dist,ddist
             attribute.  -   sort a table on a specified  asort
       - sort a table on a   specified attribute.  ........................ asort
  numeric/ - do elementary   statistical analysis on ................ stat
                  SCCS.  -   store a UNITY table under ........ uadmin
  a delta to a UNITY table   stored under SCCS.  /make ........ udelta
a version of a UNITY table   stored under SCCS.  - get ........ uget
      - convert records to   stream packet format.  .................... packet
  /records between a UNITY   table and a UNIX file.  ................ unload
             - erase UNITY   table and auxiliary files.   erase-table,et
             - check UNITY   table attributes.  .................................... ucheck
   presentation of a UNITY   table.  /formatted .................................... catalog
      -  interactive UNITY   table definition.  .................................... maketable
 more records from a UNITY   table.  - delete one or ................ delete,udelete
   and/or data for a UNITY   table.  /print description .... display,dis
  distributions on a UNITY   table.  /single and double .... dist,ddist
- change format of a UNITY   table.  ................................................................................ format
on an attribute for a UNITY   table.  /produce an index ........ index
  new records into a UNITY   table.  - insert ............................................ insert
   a UNIX file and a UNITY   table.  /records between ............ load
            print on UNITY   table.  numeric-formatted ........ nprintf
    data types.  -  define   table name,attributes, and .... table
      attribute.  - sort a   table on a specified ............................ asort
 - make a delta to a UNITY   table stored under SCCS.  ........ udelta
- get a version of a UNITY   table stored under SCCS.  ........ uget
 - edit records in a UNITY   table.  ................................................................................ uedit
enter records into a UNITY   table.  - ........................................................................ uenter
           - store a UNITY   table under SCCS.  .................................... uadmin
   presentation of a UNITY   table.  - formatted ................................ uprint,print
 and projection on a UNITY   table.  - do selection .................... uselect,select
    - compile a validation   table.  ................................................................................ valcmp
       - join two existing   tables based on regular/ ............ regjoin
      expressions on UNITY   tables.  /arithmetic ............................ compute
        two existing UNITY   tables.  - outerjoin ............................ outerjoin
of attributes on two UNITY   tables.  /set difference ............ setdiff
 - join two existing UNITY   tables.  ............................................................................ ujoin,join
            print on UNITY   tables.  - user-formatted ........ uprintf
       data from packet to   tuple format.  - converts ........ tuple
 name,attributes, and data   types.  -  define table ................ table
         - introduction to   UNITY commands and/ ................................ Intro
     - print man pages for   UNITY commands.  ............................................ uman
          - menu access to   UNITY commands.  ............................................ umenu
                   - erase   UNITY index files.  ................................ erase-index,ei
  - function to validate a   UNITY record.  .................................................... val
- unload records between a   UNITY table and a UNIX/ ................ unload
           files.  - erase   UNITY table and auxiliary ........ erase-table,et
                   - check   UNITY table attributes.  ............ ucheck
formatted presentation of a   UNITY table.  /vertically ........ catalog
            -  interactive   UNITY table definition.  ............ maketable
one or more records from a   UNITY table.  - delete .................... delete,udelete
         and/or data for a   UNITY table.  /description .... display,dis
 double distributions on a   UNITY table.  /single and ........ dist,ddist
      - change format of a   UNITY table.  ........................................................ format
index on an attribute for a   UNITY table.  /produce an ........ index
 insert new records into a   UNITY table.  - ................................................ insert
 between a UNIX file and a   UNITY table.  /load records  load
 - numeric-formatted print   UNITY table.  ................................................. nprintf
       - make a delta to a   UNITY table stored under/ ........ udelta
      - get a version of a   UNITY table stored under/ ........ uget
       - edit records in a   UNITY table.  ........................................................ uedit
    - enter records into a   UNITY table.  ........................................................ uenter
                 - store a   UNITY table under SCCS.  ............ uadmin
formatted presentation of a   UNITY table.  - ................................................ uprint,print
       and projection on a   UNITY table.  /do selection  uselect,select
 arithmetic expressions on   UNITY tables.  - compute ............ compute
  - outerjoin two existing   UNITY tables.  .................................................... outerjoin
      of attributes on two   UNITY tables.  /difference .... setdiff
       - join two existing   UNITY tables.  .................................................... ujoin,join
 - user-formatted print on   UNITY tables.  .................................................... uprintf
  - load records between a   UNIX file and a UNITY/ .................... load
between a UNITY table and a   UNIX file.  /unload records  unload
 UNITY table and a UNIX/ -   unload records between a ............ unload
          UNITY tables.  -   user-formatted print on ................ uprintf
             - function to   validate a UNITY record.  ........ val
               - compile a   validation table.  .................................... valcmp
                  - record   validator.  ................................................................ validate
  one or more/ - alter the   value of an attribute in ............ alter
    - join/split attribute   values for given/ ........................................ merge,unmerge
     stored under/ - get a   version of a UNITY table ............ uget
presentation of a UNITY/ -   vertically formatted ............................ catalog

