static char *SCCSID="@(#)Catch.c	2.1.1.4";

/*
 *   GP Library routine 
 *
 *   Written by: R. de Heij 
 *   LastEditDate="Wed Jan 13 08:33:49 1993"
 */

#if defined(__CYGWIN__)
#include <signal.h>
#else
#include <sys/signal.h>
#endif

extern void Quit();
#ifdef sun
extern void (*signal())();
static void abort_all();
#else
#if !defined(linux) && !defined(__ppc__) && !defined(__CYGWIN__) && !defined(__sgi__) && !defined(__hppa__)
extern int (*signal())();
#endif
static int abort_all();
#endif

extern int Quit_prt;

void (*Catch_function)() = (void(*)())0;/* Function to execute when catch called */
int Catch_quit = 1;		       /* Quit if catch is called, default = yes*/

#ifdef sun
static void
#else
static int
#endif
abort_all()
{
/*
 * Routine that is executed when interrupt is received
 * If catch_function is set that function will be called.
 * Then when Catch_quit is true, Quit("aborted") will be called
 * If catch_quit is not true a normal return is done
 */

    void Catch ();
    void (*ftx) ();		       /* Function to execute */

    /* switch Catch back on */
    Catch ();

    /* Execute catch function, but reset Catch_function to prohibit */
    /*  recursive calls */
    if (Catch_function != (void (*) ()) 0) {
	ftx = Catch_function;
	Catch_function = (void (*) ()) 0;
	(void) (*ftx) ();
    }

    /* If we need to quit, we quit */
    if (Catch_quit) {
	Quit_prt = 0;
	Quit ("Aborted", 0);
    }
}

void
Catch()
{
/*
 * Catch all interrupts that can be generated by the keyboard.
 * We do it only if the interrupts are not inhibitted yet.
 * This trick takes also care that the catch function can be used
 * together with the nohup command.
 * The function abort will be called when a interrupt is received.
 */

#ifdef sun
	    void     (*istat) (), (*qstat) ();  /* Signal status */
#else
    int     (*istat) (), (*qstat) ();  /* Signal status */
#endif

    istat = signal (SIGINT, abort_all);
#ifdef sun
    if (istat != (void (*) ()) SIG_DFL)
	(void) signal (SIGINT, istat);
#else
    if (istat != (int (*) ()) SIG_DFL)
	(void) signal (SIGINT, istat);
#endif
    qstat = signal (SIGQUIT, abort_all);
#ifdef sun
    if (qstat != (void (*) ()) SIG_DFL)
	(void) signal (SIGQUIT, qstat);
#else
    if (qstat != (int (*) ()) SIG_DFL)
	(void) signal (SIGQUIT, qstat);
#endif
}
