re_integer    "^[+-]{0,1}[0-9]+$"
re_fraction   "^[+-]{0,1}[0-9]*[.][0-9]+$"
re_decimal    "^[+-]{0,1}[0-9]+[.][0-9]*$"
re_attribute  "^([^/,]*[.]){0,1}[a-z_A-Z][a-z_A-Z0-9]*#{0,1}$"
re_recnum     "^([^/,]*[.]){0,1}rec#$"
re_seeknum    "^([^/,]*[.]){0,1}seek#$"
re_attr_mod   "^([^/,]*[.]){0,1}[a-z_A-Z][a-z_A-Z0-9]*:[a-z]+$"
re_hexstring  "^0[xX][a-fA-F0-9]+$"
re_attrlist   "^(([^/,]*[.]){0,1}[a-z_A-Z][a-z_A-Z0-9]*#{0,1},){1,}"
              "([^/,]*[.]){0,1}[a-z_A-Z][a-z_A-Z0-9]*#{0,1}$"
